version: "3.3"
services:
  nodered-dev:
    ports:
      - "1880:1880"
    environment:
      - TEST=abc
    build:
      context: .
    entrypoint: >
      sh -c "
      npm install --prefix /data --unsafe-perm --no-update-notifier --no-fund --only=production
      && npm --no-update-notifier --no-fund start --cache /data/.npm -- --userDir /data"
    restart: unless-stopped
